// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_twoodru8.Models;

#nullable disable

namespace Mission06_twoodru8.Migrations
{
    [DbContext(typeof(MovieFormDBContext))]
    partial class MovieFormDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Mission06_twoodru8.Models.MovieFormModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 100,
                            Category = "Action",
                            Director = "George Lucas",
                            Rating = "PG-13",
                            Title = "Star Wars: Episode III",
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 101,
                            Category = "Action",
                            Director = "George Lucas",
                            Rating = "PG",
                            Title = "Star Wars: Episode II",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 102,
                            Category = "Action",
                            Director = "George Lucas",
                            Rating = "PG",
                            Title = "Star Wars: Episode I",
                            Year = 1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
